name: "Check Pull Request"
on:
  pull_request_target:
    branches: master
    types:
      - opened
      - edited
      - synchronize

jobs:
  copy_properties:
    runs-on: macos-latest
    if: ${{ github.event.action == 'opened' }}
    steps:
      - uses: actions/checkout@v2
      - name: Download flankScripts and add it to PATH
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew :flank-scripts:download
          echo "./flank-scripts/bash" >> $GITHUB_PATH

      - name: Copy properties
        run: flankScripts github copy_issue_properties --github-token=${{ secrets.GITHUB_TOKEN }} --pr-number=${{ github.event.number }}
  check_title:
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: amannn/action-semantic-pull-request@v1.2.0
        if: github.event.pull_request.draft == false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
