name: "Generate release notes for next commit"

on: 
  workflow_dispatch:

jobs:
  generateReleaseNotes:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get all git tags
      run: |
        git fetch --prune --unshallow --tags
        git tag

    - name: Generate documentation
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: "test_runner:processCliAsciiDoc"

    - name: Gradle Build flankScripts and add it to PATH
      run: |
        ./flank-scripts/bash/buildFlankScripts.sh
        echo "::add-path::./flank-scripts/bash"

    - name: Set next release tag variable
      run: |
        TAG=$(flankScripts ci nextReleaseTag --token=${{ secrets.GITHUB_TOKEN }})
        echo "::set-env name=NEXT_RELEASE_TAG::$(echo $TAG)";

    - name: Append release note
      run: |
        flankScripts ci generateReleaseNotes --token=${{ secrets.GITHUB_TOKEN }}

    - name: Commit files and create Pull request
      id: pr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "[Automatic PR] Generate release notes"
        signoff: false
        branch: 'release/${{ env.NEXT_RELEASE_TAG }}'
        title: 'chore: release notes for ${{ env.NEXT_RELEASE_TAG }}'
        body: "Auto generated release notes for `${{ env.NEXT_RELEASE_TAG }}` by @${{ github.actor }}"
        labels: |
          automated pr
          release
        reviewers: bootstraponline,jan-gogo,pawelpasterz,adamfilipow92,piotradamczyk5,Sloox
        draft: false
